public class MathematicalClass {
    public integer addition(integer num1, integer num2) {
        integer additionResult = num1 + num2;
        return additionResult;
    }

    public integer subtraction(integer num1, integer num2) {
        integer subtractionResult = num1 - num2;
        return subtractionResult;
    }

    public integer multiplication(integer num1, integer num2){
        integer multiplicationResult = num1 * num2;
        return multiplicationResult;
    }

    public decimal division (integer num1, integer num2){
        decimal divisionResult = num1 / num2;
        return divisionResult;
    }
}